In [1]:
import torch
a = torch.FloatTensor(2,3)
b = torch.FloatTensor([2,3,4,5])
print(a)
print(b)

# torch.FloatTensor的参数可以是一个列表，也可以是一个维度值用于生产数据类型为浮点型的Tensor
# 传递给torch.FloatTensor的参数可以是一个列表，也可以是一个维度值


tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([2., 3., 4., 5.])


In [2]:
import torch
a = torch.IntTensor(2,3)
b = torch.IntTensor([2,3,4,5])
print(a)
print(b)

# torch.FloatTensor的参数可以是一个列表，也可以是一个维度值用于生产数据类型为浮点型的Tensor
# 传递给torch.FloatTensor的参数可以是一个列表，也可以是一个维度值

tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)
tensor([2, 3, 4, 5], dtype=torch.int32)


In [3]:
# torch.randn: 用于生产数据类型为浮点型且维度指定的随机Tensor, 和在Numpy中使用numpy.randn生成随机数的方法类似
# 随机生成的浮点数的取值满足均值为0、方差为1的正态分布
a = torch.randn(2,3)
print(a)

tensor([[ 0.6176, -0.3828, -0.5033],
        [ 0.5535, -0.0917, -0.3321]])


In [10]:
a = torch.arange(1,20,2)
print(a)
# torch.arange是左闭右闭，即将被弃用。 
# torch.arange是左闭右开

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])
