In [1]:
# 绝对值
import torch
a = torch.randn(2,3)
print(a)

b = torch.abs(a)
print(b)

tensor([[-0.8527, -0.9120,  3.4063],
        [-1.2442, -1.5175,  0.5093]])
tensor([[0.8527, 0.9120, 3.4063],
        [1.2442, 1.5175, 0.5093]])


In [4]:
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.add(a, b)
print(c)

d =  torch.randn(2,3)
print(d)

e =  torch.add(d,10)
print(e)

tensor([[ 0.0038,  0.4970, -0.1219],
        [-0.4175,  1.1976, -1.9916]])
tensor([[ 0.4454,  0.6767, -0.3256],
        [ 0.4690,  0.4255,  0.4370]])
tensor([[ 0.4492,  1.1737, -0.4475],
        [ 0.0514,  1.6231, -1.5547]])
tensor([[ 0.4771,  1.6389,  1.7767],
        [-0.1258,  0.1873, -0.3471]])
tensor([[10.4771, 11.6389, 11.7767],
        [ 9.8742, 10.1873,  9.6529]])


In [5]:
# 裁剪
a = torch.randn(2,3)
print(a)

b = torch.clamp(a, -0.1,0.1)
print(b)

tensor([[ 1.5234,  0.5582, -1.2324],
        [ 0.2521, -0.6549, -0.7131]])
tensor([[ 0.1000,  0.1000, -0.1000],
        [ 0.1000, -0.1000, -0.1000]])


In [6]:
# 求商
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.div(a, b)
print(c)

d =  torch.randn(2,3)
print(d)

e =  torch.div(d,10)
print(e)

tensor([[ 0.0779,  0.9835, -0.2625],
        [ 0.1043,  0.4858,  1.8302]])
tensor([[ 0.0136,  1.0331,  0.2953],
        [-2.8330, -0.7799,  0.2948]])
tensor([[ 5.7277,  0.9519, -0.8888],
        [-0.0368, -0.6229,  6.2090]])
tensor([[ 0.9158, -0.1871, -0.3211],
        [ 0.5732,  0.8233, -1.6958]])
tensor([[ 0.0916, -0.0187, -0.0321],
        [ 0.0573,  0.0823, -0.1696]])


In [7]:
# 求积
a = torch.randn(2,3)
print(a)

b = torch.randn(2,3)
print(b)

c = torch.mul(a, b)
print(c)

d =  torch.randn(2,3)
print(d)

e =  torch.mul(d,10)
print(e)

tensor([[ 0.4582,  0.4275, -0.4944],
        [ 1.1270,  0.3131,  0.6615]])
tensor([[-0.5140,  0.0857, -0.4962],
        [-1.2468,  0.3686,  0.8843]])
tensor([[-0.2355,  0.0366,  0.2453],
        [-1.4051,  0.1154,  0.5849]])
tensor([[ 0.3066,  2.0119,  2.6735],
        [ 0.3529, -0.2756,  0.4393]])
tensor([[ 3.0660, 20.1191, 26.7352],
        [ 3.5291, -2.7564,  4.3926]])


In [11]:
# 求幂
a = torch.randn(2,3)
print(a)

b = torch.pow(a,2)
print(b)

tensor([[-0.3957,  1.4506, -1.3652],
        [-0.0623, -0.8942,  1.5753]])
tensor([[0.1566, 2.1041, 1.8639],
        [0.0039, 0.7996, 2.4815]])


In [13]:
# 矩阵相乘

a = torch.randn(2,3)
print(a)

b = torch.randn(3,2)
print(b)

c = torch.mm(a, b)
print(c)

tensor([[ 0.9616,  1.2792,  0.6331],
        [ 1.0210, -1.2816, -1.1806]])
tensor([[ 1.0099, -0.0295],
        [ 0.0230,  0.2653],
        [-0.8106,  0.5378]])
tensor([[ 0.4874,  0.6514],
        [ 1.9586, -1.0050]])


In [ ]:




# 求积
# 被传入的参数中的第一个参数代表矩阵
# 第二个参数代表向量
a = torch.randn(2,3)
print(a)

b = torch.randn(3)
print(b)

c = torch.mv(a, b)
print(c)